### PR TITLE
Allow the user to pick from a list of templates to share location

### PR DESCRIPTION
**Pull request by mahula**
Hello,

like suggested in the Issues comments, I changed the line using Google Maps to use OpenStreetMaps instead.

And on the side just added localization for the German language.

What do you think about using this?

### CODE REVIEW

**Comment by pR0Ps** [comment]
Would you be able to split the localization into a separate PR?

**Comment by mahula** [comment]
Yes, I will do so.

**Comment by mahula** [comment]
Now the localization has been removed.

**Comment by pR0Ps** [comment]
So my issue with changing the URL template is that the app is supposed to be useful for the majority of people.

I would guess that the app is primarily usually used to send messages to other peoples' phones (although I don't have any data to back this up with). Since Google Maps comes preinstalled on almost every phone, it's more likely the person you are sending the link to would appreciate a Google Maps link vs. a link that will probably open in their browser (I realize that OSMAnd and other apps exist, but not at same scale).

I do agree that OSM should be a supported link (I'm a huge fan of the project and do local mapping myself), but I don't know if it should be the only link.

Ideally, the way I would like to attack this would be to provide some sort of way to switch between Google Maps link, an OSM link, a [Geo URI](https://en.wikipedia.org/wiki/Geo_URI_scheme), and maybe a custom template (see #4). That way everyone could use the most appropriate link for their situation.

**Comment by jpggithub** [comment]
The top for a user could be  to be able to select one, two, or more links between Google maps, OSM, custom, and so on. For example, if the user wants to a Google maps link AND an OSM link, he could be able to send both at the same time.
By default, Google maps could be already selected because it is evil ;-) and it is often preinstalled.
If the user wants another kind of links, he will be able to do so.

**Comment by mahula** [comment]
@pR0Ps I fully agree with you.

What about implementing a small dialog where the user can choose between Google Maps and OSM  before sending a link. I could also imagine giving the user the option to choose the preferred (combination on) links once and not ask him/her again. The coice would be saved in the app's settings, which then will be reachable via a settings activity to keep option to later change the choices made.

This also gives more reason to do the localization later in a seperate PR.

If you agree with this, I would implement that after the weekend.

**Comment by mahula** [comment]
Do you have any specific customization in mind?
What about providing several templates to the user (e.g., plain lat+long, specifications of other services) in a sub dialog of the choice dialog suggested for #13?

**Comment by pR0Ps** [comment]
Having a dialog box pop up with link options when hitting the share button would be great initial implementation (and should be pretty simple). Google Maps, OSM, and a Geo URL would be my first thoughts for template options. Just having the ability to chose one of a couple preset services would be a big leap in functionality.

A settings activity that would allow for setting up custom templates and choosing which ones would be made available when hitting the share button would be a great enhancement too. This should probably be done as a separate feature though as it adds a bit more complexity to the app (making options persist across launches, and a new settings activity, etc).

**Comment by mahula** [comment]
Okay, then I will implement the dialog box for sharing choice.

**Comment by mahula** [comment]
The list/dialog ti pick the link types from requested in #10 is done now.
The implementation of it could be improved, but this will be done when the settings activity will be implemented.

**Comment by mahula** [comment]
Should the settings activity be accessible from the toolbar menu or in a modernized fashion from the navigation drawer?

**Comment by pR0Ps** [comment]
Just having this option be a "tap what you want" would be more streamlined IMO. Having the ability to pick multiple options makes the user have to tap up to 3 times before they get to share a non-Google link (deselect Google Maps, select other, hit OK). Only having to deal with a single template also makes the code a lot easier since you only ever need to consider a single option (no need to look at multiple options and build a string).

**Pull request closed without merging**
