### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
:)

### CODE REVIEW

**Comment by pR0Ps** [comment]
Thanks! I just merged [a PR](https://github.com/pR0Ps/LocationShare/pull/29) that added an `always_ask` string, as well as removed the `pref_link_type_default` string.

Would you be able to update your PR to reflect these changes?

**Comment by Vistaus** [comment]
@pR0Ps Done! :)

**Comment by pR0Ps** [comment]
Thanks!

**Comment by pR0Ps** [comment]
@Vistaus I'm going to add a translations section to the README to credit people who contributed. What name+URL would you prefer to be credited as?

**Comment by Vistaus** [comment]
@pR0Ps 

Name: Heimen Stoffels
URL: dunno... I guess my GitHub profile URL is fine :)

**Comment by Vistaus** [comment]
Hi @mahula,

that's fine :)

**Pull request merged**
