### PR TITLE
Some maintenance

### PR DESCRIPTION
**Pull request by TacoTheDank**
- Android Studio 3.1.4 -> 3.2.1
- Gradle 4.4 -> 4.10.3
- Compile 28
- Java 1.8 compatibility
- Invert validLocation as it is always inverted
- Update README.md badges
- Migrate app to appCompat
- Migrate to AndroidX

### CODE REVIEW

**Comment by TacoTheDank** [comment]
It is actually a bit outdated; I had created a pull request to fix this issue but it has yet to be noticed lol. If you enter ```https://f-droid.org/badge/get-it-on.png``` into a new tab, the link updates to ```https://fdroid.gitlab.io/artwork/badge/get-it-on.png```, idk why.

**Comment by TacoTheDank** [comment]
Redid commits to avoid revert commits; I don't like revert commits lol

**Comment by pR0Ps** [comment]
Thanks!

**Comment by TacoTheDank** [comment]
ye

**Comment by TacoTheDank** [comment]
You should probably tag a new release as well, just because

**Pull request merged**
