### PR TITLE
Fix interchanged assignment of latitude and longitude in TextView

### PR DESCRIPTION
**Pull request by mahula**

### CODE REVIEW

**Comment by pR0Ps** [comment]
Wow, nice catch, I can't believe I missed that.

Would you mind rebasing this branch directly off 434ed8e to remove those merge commits?

**Comment by mahula** [comment]
Thank you for the help.

*git fetch upstream' results in Permission denied (publickey).

**Comment by pR0Ps** [comment]
You're sure you added `https://github.com/pR0Ps/LocationShare.git` as the remote? That error would only happen if you added a `git@github.com` remote.

**Comment by mahula** [comment]
Now it should have worked.

**Comment by mahula** [comment]
Now this branch is rebased directly off 434ed8e.
Thanx for your patience and helpful advice.

**Pull request merged**
